version: '3.9'

services:
  backend:
    build:
      context: ./server
    ports:
      - "5001:5001"  # Backend exposé sur le port 5001
    volumes:
      - ./server:/usr/src/app
    depends_on:
      - db
    environment:
      - DB_HOST=db  # Le nom du service MySQL dans Docker (pas localhost)
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=gestion_sante
    command: ["npm", "start"]

  frontend:
    build:
      context: ./client
    ports:
      - "3000:3000"  # client exposé sur le port 3000
    volumes:
      - ./client:/usr/src/app
    command: ["npm", "start"]

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_sante
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "8889:3306"  # Mappe le port MySQL interne (3306) au port MAMP (8889)

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"  # PhpMyAdmin accessible sur http://localhost:8080
    environment:
      PMA_HOST: db  # Le service MySQL (db) comme hôte de la base de données

volumes:
  db_data:

